name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: left
        uses: lowlighter/metrics@latest
        with:
          filename: left.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: tsukasa-u
          template: classic
          base: header, activity, community, repositories, metadata
          config_padding: 8 + 20%, 8 + 20%
          config_timezone: Asia/Tokyo

          plugin_habits: yes
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 8
          plugin_habits_languages_threshold: 0%

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes

          plugin_notable: yes
          plugin_notable_from: organization
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
          plugin_notable_self: yes
          plugin_notable_types: commit

          
      - name: right
        uses: lowlighter/metrics@latest
        with:
          filename: right.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: 
          config_padding: 8 + 20%, 8 + 20%
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_stars: yes
          plugin_stars_limit: 4

          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

      # - name: general
      #   uses: lowlighter/metrics@latest
      #   with:
      #     filename: center.svg
      #     token: ${{ secrets.METRICS_TOKEN }}

      #     # Options
      #     user: tsukasa-u
      #     template: classic
      #     base: header, activity, community, repositories, metadata
      #     config_padding: 8 + 20%, 8 + 20%
      #     config_timezone: Asia/Tokyo
      #     config_display: columns

      #     plugin_habits: yes
      #     plugin_habits_charts_type: classic
      #     plugin_habits_days: 14
      #     plugin_habits_facts: yes
      #     plugin_habits_from: 200
      #     plugin_habits_languages_limit: 8
      #     plugin_habits_languages_threshold: 0%

      #     plugin_languages: yes
      #     plugin_languages_analysis_timeout: 15
      #     plugin_languages_categories: markup, programming
      #     plugin_languages_colors: github
      #     plugin_languages_details: bytes-size, percentage
      #     plugin_languages_limit: 8
      #     plugin_languages_recent_categories: markup, programming
      #     plugin_languages_recent_days: 14
      #     plugin_languages_recent_load: 300
      #     plugin_languages_sections: most-used
      #     plugin_languages_threshold: 0%

      #     plugin_notable: yes
      #     plugin_notable_from: organization
      #     plugin_notable_indepth: yes
      #     plugin_notable_repositories: yes
      #     plugin_notable_self: yes
      #     plugin_notable_types: commit

      #     plugin_isocalendar: yes
      #     plugin_isocalendar_duration: half-year

      #     plugin_stars: yes
      #     plugin_stars_limit: 4

      #     plugin_activity: yes
      #     plugin_activity_days: 14
      #     plugin_activity_filter: all
      #     plugin_activity_limit: 5
      #     plugin_activity_load: 300
      #     plugin_activity_visibility: all
